#include "EDF.h"

EDFStruct_t Tasks_EDFStructsArray[EDF_NUMBER_OF_TASKS] = {
	{TASK1_NOM_DEADLINE, 0U, 0U, TASK1_PERIOD},
	{TASK2_NOM_DEADLINE, 0U, 0U, TASK2_PERIOD},
	{TASK3_NOM_DEADLINE, 0U, 0U, TASK3_PERIOD},	
};


